### ISSUE TITLE
网页授权问题

### ISSUE THREAD

**Issue by wblbird** [jianyan74/yii2-easy-wechat#4]
作为一个初级开发者~帮忙看下哪里不对
要写一个微信网页授权，照着您的示例
params.php
` // ...
        'oauth' => [
            'scopes'   => ['snsapi_userinfo'],
            'callback' => '',
        ],`

业务页
`    public function actionIndexwx()
    {

        if(Yii::$app->wechat->isWechat && !Yii::$app->wechat->isAuthorized())
        {
            return Yii::$app->wechat->authorizeRequired()->send();
        }

        $user=Yii::$app->session->get('wechatUser');
        var_dump($user);die;
       
        $model = Article::find()->orderBy('id desc')->one();
        return $this->render('indexwx', [
            'model' => $model,
        ]);
    }`
callback页面还要写吗？
这样的话各种错误额，直接微信里打开显示，appid参数错误，
求详细示例~

**Comment by jianyan74** [comment]
callback 要写 设置为当前页面，appid参数错误代表你没有配置好参数，注意看文档说明配置好参数，实际案例看下https://github.com/jianyan74/rageframe2
