### ISSUE TITLE
怎么自定义回调地址

### ISSUE THREAD

**Issue by ruikc** [jianyan74/yii2-easy-wechat#5]
```
public function authorizeRequired()
    {
        if (Yii::$app->request->get('code')) {
            // callback and authorize
            return $this->authorize($this->app->oauth->user());
        } else {
            // redirect to wechat authorize page
            $this->setReturnUrl(Yii::$app->request->getUrl());
            return Yii::$app->response->redirect($this->app->oauth->redirect()->getTargetUrl());
        }
    }
```
setReturnUrl能添加个判断吗？我现在想自定义回调地址都控制不了，现在自定义回调地址

**Comment by ruikc** [comment]
![image](https://user-images.githubusercontent.com/7445875/63841904-4035a880-c9b6-11e9-811b-2c72c2c7204c.png)
这个方法有个默认参数，传一下吧，现在returnUrl只有能得到用户信息成功后，能去调用，我现在需要授权后就能调用，然后自己获取用户信息

**Comment by jianyan74** [comment]
`'oauth' => [
                'scopes' => ['snsapi_userinfo'],
                'callback' => ‘’,  // 在配置的时候可以加回调地址
            ]`

**Comment by ruikc** [comment]
我是动态的回调链接，也可以？

**Comment by jianyan74** [comment]
初始化调用之前动态改就行

**Comment by ruikc** [comment]
我直接使用Easywechat的方法了，我现在拿到用户信息之后，不需要跳转，跳转在拿到用户信息之前来处理的
