### ISSUE TITLE
微信网页授权问题

### ISSUE THREAD

**Issue by dazzulay** [jianyan74/yii2-easy-wechat#7]
\jianyan74\yii2-easy-wechat\src\Wechat.php
105行有问题
```
return Yii::$app->response->redirect($this->app->oauth->redirect()->getTargetUrl());
```
应改成
```
return Yii::$app->response->redirect($this->app->oauth->redirect(Yii::$app->request->absoluteUrl)->getTargetUrl());
```
否则无法跳转
比如 http://www.example.com/some/path/index.php/test/index  中调用了
```
if (Yii::$app->wechat->isWechat && !Yii::$app->wechat->isAuthorized()) {
    return Yii::$app->wechat->authorizeRequired()->send();
}
```

其中会返回到
http://www.example.com/?code=xxx&state=xxx
这样就不能往下走了

需要加上
Yii::$app->request->absoluteUrl
才能正常返回

**Comment by jianyan74** [comment]
我这边是都可以正常的，你这边是不是没有做伪静态导致丢失了

**Comment by dazzulay** [comment]
> 我这边是都可以正常的，你这边是不是没有做伪静态导致丢失了

我这边是一个域名下面会有多个应用，所以需要绝对地址

**Comment by jianyan74** [comment]
后续我这边测试下，没有问题会加上绝对地址

**Comment by phpcws** [comment]
确实有这个问题存在

**Comment by jianyan74** [comment]
已修复
